--
-- EnjoyTrip Backend — DB Schema
--
-- 이 파일은 처음 프로젝트를 세팅하는 개발자를 위한 DB 초기화 스크립트입니다.
-- Flyway 마이그레이션 히스토리(flyway_schema_history)도 함께 포함되어 있어,
-- 이 파일로 DB를 초기화한 후 앱을 실행하면 Flyway가 마이그레이션을 중복 적용하지 않습니다.
--
-- 사용법:
--   psql -U <user> -d <dbname> -f DB_schema.sql
--
-- 전제 조건:
--   - PostgreSQL 17+
--   - postgis 확장 설치 (docker-compose.yml의 enjoytrip-postgis-pgvector 이미지 사용)
--   - pgvector 확장 설치 (위 이미지에 포함)
--
-- Generated from database version 17.5 (Debian 17.5-1.pgdg110+1)
-- Schema version: V25 (add_course_invitations)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attraction_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attraction_embeddings (
    id bigint NOT NULL,
    attraction_id bigint NOT NULL,
    embedding public.vector(1536),
    source_version character varying(128) NOT NULL,
    source_text_hash character varying(64) NOT NULL,
    embedding_dimension integer NOT NULL,
    provider character varying(64) NOT NULL,
    model character varying(128) NOT NULL,
    status character varying(20) NOT NULL,
    failure_code character varying(128),
    failure_message character varying(1000),
    attempt_count integer DEFAULT 0 NOT NULL,
    last_attempted_at timestamp(6) without time zone,
    embedded_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    embedding_input text,
    CONSTRAINT chk_attraction_embeddings_attempt_count CHECK ((attempt_count >= 0)),
    CONSTRAINT chk_attraction_embeddings_dimension CHECK ((embedding_dimension = 1536)),
    CONSTRAINT chk_attraction_embeddings_hash CHECK ((char_length((source_text_hash)::text) = 64)),
    CONSTRAINT chk_attraction_embeddings_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'EMBEDDED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: attraction_embeddings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attraction_embeddings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attraction_embeddings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attraction_popularity_stats; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attraction_popularity_stats (
    attraction_id bigint NOT NULL,
    rating_count integer DEFAULT 0 NOT NULL,
    average_rating numeric(3,2) DEFAULT 0 NOT NULL,
    view_count integer DEFAULT 0 NOT NULL,
    course_add_count integer DEFAULT 0 NOT NULL,
    popularity_score numeric(12,4) DEFAULT 0 NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    save_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT chk_attraction_popularity_stats_average_rating CHECK (((average_rating >= (0)::numeric) AND (average_rating <= (5)::numeric))),
    CONSTRAINT chk_attraction_popularity_stats_course_add_count CHECK ((course_add_count >= 0)),
    CONSTRAINT chk_attraction_popularity_stats_popularity_score CHECK ((popularity_score >= (0)::numeric)),
    CONSTRAINT chk_attraction_popularity_stats_rating_count CHECK ((rating_count >= 0)),
    CONSTRAINT chk_attraction_popularity_stats_save_count CHECK ((save_count >= 0)),
    CONSTRAINT chk_attraction_popularity_stats_view_count CHECK ((view_count >= 0))
);


--
-- Name: attraction_ratings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attraction_ratings (
    id bigint NOT NULL,
    attraction_id bigint NOT NULL,
    rating integer NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone,
    member_id bigint NOT NULL,
    CONSTRAINT chk_attraction_ratings_rating CHECK (((rating >= 1) AND (rating <= 5)))
);


--
-- Name: attraction_ratings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attraction_ratings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attraction_ratings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attraction_saves; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attraction_saves (
    id bigint NOT NULL,
    attraction_id bigint NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    member_id bigint NOT NULL
);


--
-- Name: attraction_saves_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attraction_saves ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attraction_saves_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tags (
    id bigint NOT NULL,
    name character varying(64) NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: attraction_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attraction_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attractions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attractions (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    addr1 character varying(512),
    addr2 character varying(512),
    zipcode character varying(20),
    tel character varying(100),
    first_image character varying(1024),
    first_image2 character varying(1024),
    read_count integer DEFAULT 0,
    sido_code integer,
    gugun_code integer,
    mlevel character varying(20),
    content_type_id character varying(20),
    overview text,
    location public.geometry(Point,4326),
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    updated_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    duplicate_of_attraction_id bigint,
    duplicate_reason text,
    CONSTRAINT chk_attractions_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'HIDDEN'::character varying])::text[])))
);


--
-- Name: auth_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_logs (
    id bigint NOT NULL,
    event_type character varying(20) NOT NULL,
    logged_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL
);


--
-- Name: auth_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: batch_job_execution; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_job_execution (
    job_execution_id bigint NOT NULL,
    version bigint,
    job_instance_id bigint NOT NULL,
    create_time timestamp without time zone NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    status character varying(10),
    exit_code character varying(2500),
    exit_message character varying(2500),
    last_updated timestamp without time zone
);


--
-- Name: batch_job_execution_context; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_job_execution_context (
    job_execution_id bigint NOT NULL,
    short_context character varying(2500) NOT NULL,
    serialized_context text
);


--
-- Name: batch_job_execution_params; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_job_execution_params (
    job_execution_id bigint NOT NULL,
    parameter_name character varying(100) NOT NULL,
    parameter_type character varying(100) NOT NULL,
    parameter_value character varying(2500),
    identifying character(1) NOT NULL
);


--
-- Name: batch_job_execution_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.batch_job_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: batch_job_instance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_job_instance (
    job_instance_id bigint NOT NULL,
    version bigint,
    job_name character varying(100) NOT NULL,
    job_key character varying(32) NOT NULL
);


--
-- Name: batch_job_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.batch_job_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: batch_step_execution; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_step_execution (
    step_execution_id bigint NOT NULL,
    version bigint NOT NULL,
    step_name character varying(100) NOT NULL,
    job_execution_id bigint NOT NULL,
    create_time timestamp without time zone NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    status character varying(10),
    commit_count bigint,
    read_count bigint,
    filter_count bigint,
    write_count bigint,
    read_skip_count bigint,
    write_skip_count bigint,
    process_skip_count bigint,
    rollback_count bigint,
    exit_code character varying(2500),
    exit_message character varying(2500),
    last_updated timestamp without time zone
);


--
-- Name: batch_step_execution_context; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.batch_step_execution_context (
    step_execution_id bigint NOT NULL,
    short_context character varying(2500) NOT NULL,
    serialized_context text
);


--
-- Name: batch_step_execution_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.batch_step_execution_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: course_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_embeddings (
    id bigint NOT NULL,
    course_id character varying(128) NOT NULL,
    description text,
    embedding public.vector(1536),
    dominant_category character varying(30),
    source_version character varying(128) NOT NULL,
    source_hash character varying(64) NOT NULL,
    embedding_dimension integer NOT NULL,
    provider character varying(64) NOT NULL,
    model character varying(128) NOT NULL,
    status character varying(20) NOT NULL,
    failure_code character varying(128),
    failure_message character varying(1000),
    attempt_count integer DEFAULT 0 NOT NULL,
    last_attempted_at timestamp(6) without time zone,
    embedded_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_course_embeddings_dimension CHECK ((embedding_dimension = 1536)),
    CONSTRAINT chk_course_embeddings_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'PROCESSING'::character varying, 'EMBEDDED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: course_embeddings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_embeddings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_embeddings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_invitations (
    id bigint NOT NULL,
    course_id character varying(128) NOT NULL,
    inviter_member_id bigint NOT NULL,
    invitee_member_id bigint NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: course_invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_items (
    id bigint NOT NULL,
    course_id character varying(128) NOT NULL,
    item_type character varying(20) NOT NULL,
    attraction_id bigint,
    note_id bigint,
    "position" integer NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    distance_to_next integer,
    duration_to_next integer,
    CONSTRAINT chk_course_items_distance_to_next CHECK (((distance_to_next IS NULL) OR (distance_to_next >= 0))),
    CONSTRAINT chk_course_items_duration_to_next CHECK (((duration_to_next IS NULL) OR (duration_to_next >= 0))),
    CONSTRAINT chk_course_items_position CHECK (("position" > 0)),
    CONSTRAINT chk_course_items_target CHECK (((((item_type)::text = 'ATTRACTION'::text) AND (attraction_id IS NOT NULL) AND (note_id IS NULL)) OR (((item_type)::text = 'NOTE'::text) AND (attraction_id IS NULL) AND (note_id IS NOT NULL)))),
    CONSTRAINT chk_course_items_type CHECK (((item_type)::text = ANY ((ARRAY['ATTRACTION'::character varying, 'NOTE'::character varying])::text[])))
);


--
-- Name: course_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_reports (
    id bigint NOT NULL,
    course_id character varying(128) NOT NULL,
    reason character varying(50) NOT NULL,
    detail text,
    status character varying(20) DEFAULT 'OPEN'::character varying NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reporter_member_id bigint NOT NULL,
    CONSTRAINT chk_course_reports_status CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'REVIEWED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: course_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_saves; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_saves (
    id bigint NOT NULL,
    course_id character varying(128) NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    member_id bigint NOT NULL
);


--
-- Name: course_saves_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_saves ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_saves_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: course_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_tags (
    course_id character varying(128) NOT NULL,
    tag_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: course_views; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.course_views (
    id bigint NOT NULL,
    course_id character varying(128) NOT NULL,
    member_id bigint NOT NULL,
    viewed_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: course_views_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.course_views ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.course_views_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.courses (
    id character varying(128) NOT NULL,
    title character varying(120) NOT NULL,
    region_name character varying(100),
    share_image_url character varying(1024),
    route_line public.geometry(LineString,4326),
    started_at timestamp(6) without time zone,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    start_location public.geometry(Point,4326),
    owner_member_id bigint NOT NULL,
    date character varying(32),
    thumbnail_url character varying(1024)
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: friendships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.friendships (
    id bigint NOT NULL,
    status character varying(20) DEFAULT 'PENDING'::character varying NOT NULL,
    requested_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    responded_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone,
    requester_member_id bigint NOT NULL,
    addressee_member_id bigint NOT NULL,
    CONSTRAINT chk_friendships_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying, 'REJECTED'::character varying, 'DELETED'::character varying])::text[])))
);


--
-- Name: friendships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.friendships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.friendships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member_profile_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_profile_embeddings (
    id bigint NOT NULL,
    member_id bigint NOT NULL,
    profile_description text,
    embedding public.vector(1536),
    source_version character varying(128) NOT NULL,
    source_hash character varying(64) NOT NULL,
    embedding_dimension integer NOT NULL,
    provider character varying(64) NOT NULL,
    model character varying(128) NOT NULL,
    status character varying(20) NOT NULL,
    failure_code character varying(128),
    failure_message character varying(1000),
    attempt_count integer DEFAULT 0 NOT NULL,
    last_attempted_at timestamp(6) without time zone,
    embedded_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_member_profile_embeddings_dimension CHECK ((embedding_dimension = 1536)),
    CONSTRAINT chk_member_profile_embeddings_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'EMBEDDED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: member_profile_embeddings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member_profile_embeddings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_profile_embeddings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.members (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    updated_at timestamp(6) without time zone,
    nickname character varying(30),
    profile_image_url character varying(512),
    profile_image_object_key character varying(512),
    role character varying(20) DEFAULT 'USER'::character varying NOT NULL,
    CONSTRAINT chk_members_role CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note_embeddings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note_embeddings (
    id bigint NOT NULL,
    note_id bigint NOT NULL,
    embedding public.vector(1536),
    embedding_input text,
    source_version character varying(128) NOT NULL,
    source_text_hash character varying(64) NOT NULL,
    embedding_dimension integer NOT NULL,
    provider character varying(64) NOT NULL,
    model character varying(128) NOT NULL,
    status character varying(20) NOT NULL,
    failure_code character varying(128),
    failure_message character varying(1000),
    attempt_count integer DEFAULT 0 NOT NULL,
    last_attempted_at timestamp(6) without time zone,
    embedded_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_note_embeddings_dimension CHECK ((embedding_dimension = 1536)),
    CONSTRAINT chk_note_embeddings_status CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'EMBEDDED'::character varying, 'FAILED'::character varying])::text[])))
);


--
-- Name: note_embeddings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.note_embeddings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_embeddings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note_reports (
    id bigint NOT NULL,
    note_id bigint NOT NULL,
    reason character varying(50) NOT NULL,
    detail text,
    status character varying(20) DEFAULT 'OPEN'::character varying NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    reporter_member_id bigint NOT NULL,
    CONSTRAINT chk_note_reports_status CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'REVIEWED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: note_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.note_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note_saves; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note_saves (
    id bigint NOT NULL,
    note_id bigint NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    member_id bigint NOT NULL
);


--
-- Name: note_saves_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.note_saves ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_saves_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: note_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.note_tags (
    id bigint NOT NULL,
    note_id bigint NOT NULL,
    tag_id bigint NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: note_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.note_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.note_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notes (
    id bigint NOT NULL,
    title character varying(100) NOT NULL,
    content text NOT NULL,
    category character varying(30) DEFAULT 'UNCATEGORIZED'::character varying NOT NULL,
    visibility character varying(20) DEFAULT 'PUBLIC'::character varying NOT NULL,
    location public.geometry(Point,4326) NOT NULL,
    latitude numeric(10,7) NOT NULL,
    longitude numeric(10,7) NOT NULL,
    region_name character varying(100),
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    image_object_key character varying(512),
    image_url character varying(1024),
    image_content_type character varying(100),
    author_member_id bigint NOT NULL,
    CONSTRAINT chk_notes_category CHECK (((category)::text = ANY ((ARRAY['BEST'::character varying, 'MUSIC'::character varying, 'BOOK'::character varying, 'MOVIE'::character varying, 'TIP'::character varying, 'TRANSIT_TIP'::character varying, 'UNCATEGORIZED'::character varying])::text[]))),
    CONSTRAINT chk_notes_image_content_type CHECK (((image_content_type IS NULL) OR ((image_content_type)::text ~~ 'image/%'::text))),
    CONSTRAINT chk_notes_latitude CHECK (((latitude >= ('-90'::integer)::numeric) AND (latitude <= (90)::numeric))),
    CONSTRAINT chk_notes_longitude CHECK (((longitude >= ('-180'::integer)::numeric) AND (longitude <= (180)::numeric))),
    CONSTRAINT chk_notes_single_image_reference_pair CHECK ((((image_object_key IS NULL) AND (image_url IS NULL) AND (image_content_type IS NULL)) OR ((image_object_key IS NOT NULL) AND (image_url IS NOT NULL) AND (image_content_type IS NOT NULL)))),
    CONSTRAINT chk_notes_status CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'HIDDEN'::character varying, 'DELETED'::character varying])::text[]))),
    CONSTRAINT chk_notes_visibility CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'FRIENDS'::character varying, 'PRIVATE'::character varying])::text[])))
);


--
-- Name: notes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    type character varying(50) NOT NULL,
    reference_type character varying(50) NOT NULL,
    reference_id bigint NOT NULL,
    payload text,
    read_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp(6) without time zone,
    recipient_member_id bigint NOT NULL,
    CONSTRAINT chk_notifications_reference_type CHECK (((reference_type)::text = ANY ((ARRAY['FRIENDSHIP'::character varying, 'COURSE_INVITATION'::character varying])::text[]))),
    CONSTRAINT chk_notifications_type CHECK (((type)::text = ANY ((ARRAY['FRIEND_REQUEST_RECEIVED'::character varying, 'COURSE_INVITATION_RECEIVED'::character varying])::text[])))
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attraction_embeddings attraction_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_embeddings
    ADD CONSTRAINT attraction_embeddings_pkey PRIMARY KEY (id);


--
-- Name: attraction_popularity_stats attraction_popularity_stats_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_popularity_stats
    ADD CONSTRAINT attraction_popularity_stats_pkey PRIMARY KEY (attraction_id);


--
-- Name: attraction_ratings attraction_ratings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_ratings
    ADD CONSTRAINT attraction_ratings_pkey PRIMARY KEY (id);


--
-- Name: attraction_saves attraction_saves_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_saves
    ADD CONSTRAINT attraction_saves_pkey PRIMARY KEY (id);


--
-- Name: tags attraction_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT attraction_tags_pkey PRIMARY KEY (id);


--
-- Name: attractions attractions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attractions
    ADD CONSTRAINT attractions_pkey PRIMARY KEY (id);


--
-- Name: auth_logs auth_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_logs
    ADD CONSTRAINT auth_logs_pkey PRIMARY KEY (id);


--
-- Name: batch_job_execution_context batch_job_execution_context_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_job_execution_context
    ADD CONSTRAINT batch_job_execution_context_pkey PRIMARY KEY (job_execution_id);


--
-- Name: batch_job_execution batch_job_execution_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_job_execution
    ADD CONSTRAINT batch_job_execution_pkey PRIMARY KEY (job_execution_id);


--
-- Name: batch_job_instance batch_job_instance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_job_instance
    ADD CONSTRAINT batch_job_instance_pkey PRIMARY KEY (job_instance_id);


--
-- Name: batch_step_execution_context batch_step_execution_context_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_step_execution_context
    ADD CONSTRAINT batch_step_execution_context_pkey PRIMARY KEY (step_execution_id);


--
-- Name: batch_step_execution batch_step_execution_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_step_execution
    ADD CONSTRAINT batch_step_execution_pkey PRIMARY KEY (step_execution_id);


--
-- Name: course_embeddings course_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_embeddings
    ADD CONSTRAINT course_embeddings_pkey PRIMARY KEY (id);


--
-- Name: course_invitations course_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_invitations
    ADD CONSTRAINT course_invitations_pkey PRIMARY KEY (id);


--
-- Name: course_items course_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_items
    ADD CONSTRAINT course_items_pkey PRIMARY KEY (id);


--
-- Name: course_reports course_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reports
    ADD CONSTRAINT course_reports_pkey PRIMARY KEY (id);


--
-- Name: course_saves course_saves_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_saves
    ADD CONSTRAINT course_saves_pkey PRIMARY KEY (id);


--
-- Name: course_views course_views_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_views
    ADD CONSTRAINT course_views_pkey PRIMARY KEY (id);


--
-- Name: courses courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT courses_pkey PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: friendships friendships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT friendships_pkey PRIMARY KEY (id);


--
-- Name: batch_job_instance job_inst_un; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_job_instance
    ADD CONSTRAINT job_inst_un UNIQUE (job_name, job_key);


--
-- Name: member_profile_embeddings member_profile_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_profile_embeddings
    ADD CONSTRAINT member_profile_embeddings_pkey PRIMARY KEY (id);


--
-- Name: members members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT members_pkey PRIMARY KEY (id);


--
-- Name: note_embeddings note_embeddings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_embeddings
    ADD CONSTRAINT note_embeddings_pkey PRIMARY KEY (id);


--
-- Name: note_reports note_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_reports
    ADD CONSTRAINT note_reports_pkey PRIMARY KEY (id);


--
-- Name: note_saves note_saves_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_saves
    ADD CONSTRAINT note_saves_pkey PRIMARY KEY (id);


--
-- Name: note_tags note_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tags
    ADD CONSTRAINT note_tags_pkey PRIMARY KEY (id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: course_tags pk_course_tags; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tags
    ADD CONSTRAINT pk_course_tags PRIMARY KEY (course_id, tag_id);


--
-- Name: attraction_embeddings uk_attraction_embeddings_attraction; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_embeddings
    ADD CONSTRAINT uk_attraction_embeddings_attraction UNIQUE (attraction_id);


--
-- Name: attraction_ratings uk_attraction_ratings_attraction_member; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_ratings
    ADD CONSTRAINT uk_attraction_ratings_attraction_member UNIQUE (attraction_id, member_id);


--
-- Name: attraction_saves uk_attraction_saves_attraction_member; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_saves
    ADD CONSTRAINT uk_attraction_saves_attraction_member UNIQUE (attraction_id, member_id);


--
-- Name: tags uk_attraction_tags_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT uk_attraction_tags_name UNIQUE (name);


--
-- Name: course_invitations uk_ci_course_invitee; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_invitations
    ADD CONSTRAINT uk_ci_course_invitee UNIQUE (course_id, invitee_member_id);


--
-- Name: course_embeddings uk_course_embeddings_course; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_embeddings
    ADD CONSTRAINT uk_course_embeddings_course UNIQUE (course_id);


--
-- Name: course_items uk_course_items_course_id_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_items
    ADD CONSTRAINT uk_course_items_course_id_id UNIQUE (course_id, id);


--
-- Name: course_items uk_course_items_course_position; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_items
    ADD CONSTRAINT uk_course_items_course_position UNIQUE (course_id, "position");


--
-- Name: course_reports uk_course_reports_course_reporter; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reports
    ADD CONSTRAINT uk_course_reports_course_reporter UNIQUE (course_id, reporter_member_id);


--
-- Name: course_saves uk_course_saves_course_member; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_saves
    ADD CONSTRAINT uk_course_saves_course_member UNIQUE (course_id, member_id);


--
-- Name: member_profile_embeddings uk_member_profile_embeddings_member; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_profile_embeddings
    ADD CONSTRAINT uk_member_profile_embeddings_member UNIQUE (member_id);


--
-- Name: members uk_members_email; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.members
    ADD CONSTRAINT uk_members_email UNIQUE (email);


--
-- Name: note_embeddings uk_note_embeddings_note; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_embeddings
    ADD CONSTRAINT uk_note_embeddings_note UNIQUE (note_id);


--
-- Name: note_reports uk_note_reports_note_reporter; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_reports
    ADD CONSTRAINT uk_note_reports_note_reporter UNIQUE (note_id, reporter_member_id);


--
-- Name: note_saves uk_note_saves_note_member; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_saves
    ADD CONSTRAINT uk_note_saves_note_member UNIQUE (note_id, member_id);


--
-- Name: note_tags uk_note_tags_note_tag; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tags
    ADD CONSTRAINT uk_note_tags_note_tag UNIQUE (note_id, tag_id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_attraction_embeddings_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attraction_embeddings_source ON public.attraction_embeddings USING btree (source_version, source_text_hash);


--
-- Name: idx_attraction_embeddings_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attraction_embeddings_status ON public.attraction_embeddings USING btree (status);


--
-- Name: idx_attraction_popularity_stats_score; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attraction_popularity_stats_score ON public.attraction_popularity_stats USING btree (popularity_score DESC, attraction_id);


--
-- Name: idx_attraction_ratings_attraction; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attraction_ratings_attraction ON public.attraction_ratings USING btree (attraction_id);


--
-- Name: idx_attraction_saves_attraction; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attraction_saves_attraction ON public.attraction_saves USING btree (attraction_id);


--
-- Name: idx_attraction_saves_member_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attraction_saves_member_created ON public.attraction_saves USING btree (member_id, created_at DESC);


--
-- Name: idx_attractions_area; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attractions_area ON public.attractions USING btree (sido_code, gugun_code);


--
-- Name: idx_attractions_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attractions_location ON public.attractions USING gist (location);


--
-- Name: idx_attractions_public_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attractions_public_status ON public.attractions USING btree (status, deleted_at, duplicate_of_attraction_id, id);


--
-- Name: idx_auth_logs_member_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_auth_logs_member_id ON public.auth_logs USING btree (member_id);


--
-- Name: idx_ci_invitee_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ci_invitee_status ON public.course_invitations USING btree (invitee_member_id, status);


--
-- Name: idx_course_embeddings_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_embeddings_status ON public.course_embeddings USING btree (status);


--
-- Name: idx_course_items_attraction; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_items_attraction ON public.course_items USING btree (attraction_id);


--
-- Name: idx_course_items_course_position; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_items_course_position ON public.course_items USING btree (course_id, "position");


--
-- Name: idx_course_items_note; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_items_note ON public.course_items USING btree (note_id);


--
-- Name: idx_course_reports_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_reports_status_created ON public.course_reports USING btree (status, created_at DESC);


--
-- Name: idx_course_saves_course; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_saves_course ON public.course_saves USING btree (course_id);


--
-- Name: idx_course_saves_member_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_saves_member_created ON public.course_saves USING btree (member_id, created_at DESC);


--
-- Name: idx_course_views_member_viewed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_course_views_member_viewed ON public.course_views USING btree (member_id, viewed_at DESC);


--
-- Name: idx_courses_owner_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_courses_owner_created ON public.courses USING btree (owner_member_id, created_at DESC);


--
-- Name: idx_courses_region_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_courses_region_created ON public.courses USING btree (region_name, created_at DESC);


--
-- Name: idx_courses_route_line; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_courses_route_line ON public.courses USING gist (route_line);


--
-- Name: idx_courses_start_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_courses_start_location ON public.courses USING gist (start_location) WHERE ((start_location IS NOT NULL) AND (deleted_at IS NULL));


--
-- Name: idx_friendships_addressee_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_friendships_addressee_status ON public.friendships USING btree (addressee_member_id, status);


--
-- Name: idx_friendships_requester_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_friendships_requester_status ON public.friendships USING btree (requester_member_id, status);


--
-- Name: idx_member_profile_embeddings_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_member_profile_embeddings_status ON public.member_profile_embeddings USING btree (status);


--
-- Name: idx_members_profile_image_object_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_members_profile_image_object_key ON public.members USING btree (profile_image_object_key) WHERE (profile_image_object_key IS NOT NULL);


--
-- Name: idx_note_embeddings_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_note_embeddings_status ON public.note_embeddings USING btree (status);


--
-- Name: idx_note_reports_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_note_reports_status_created ON public.note_reports USING btree (status, created_at DESC);


--
-- Name: idx_note_saves_member_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_note_saves_member_created ON public.note_saves USING btree (member_id, created_at DESC);


--
-- Name: idx_note_tags_note_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_note_tags_note_id ON public.note_tags USING btree (note_id);


--
-- Name: idx_notes_author_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notes_author_created ON public.notes USING btree (author_member_id, created_at DESC);


--
-- Name: idx_notes_category_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notes_category_created ON public.notes USING btree (category, created_at DESC);


--
-- Name: idx_notes_image_object_key; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notes_image_object_key ON public.notes USING btree (image_object_key) WHERE (image_object_key IS NOT NULL);


--
-- Name: idx_notes_location; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notes_location ON public.notes USING gist (location);


--
-- Name: idx_notes_recent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notes_recent ON public.notes USING btree (created_at DESC);


--
-- Name: idx_notes_visibility_status_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notes_visibility_status_created ON public.notes USING btree (visibility, status, created_at DESC);


--
-- Name: idx_notifications_recipient_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_recipient_created_at ON public.notifications USING btree (recipient_member_id, created_at DESC);


--
-- Name: idx_notifications_recipient_read_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_recipient_read_at ON public.notifications USING btree (recipient_member_id, read_at);


--
-- Name: uk_friendships_member_pair_active; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_friendships_member_pair_active ON public.friendships USING btree (LEAST(requester_member_id, addressee_member_id), GREATEST(requester_member_id, addressee_member_id)) WHERE ((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACCEPTED'::character varying])::text[]));


--
-- Name: uk_notifications_business_reference; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_notifications_business_reference ON public.notifications USING btree (recipient_member_id, type, reference_type, reference_id);


--
-- Name: attraction_embeddings fk_attraction_embeddings_attraction; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_embeddings
    ADD CONSTRAINT fk_attraction_embeddings_attraction FOREIGN KEY (attraction_id) REFERENCES public.attractions(id) ON DELETE CASCADE;


--
-- Name: attraction_popularity_stats fk_attraction_popularity_stats_attraction; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_popularity_stats
    ADD CONSTRAINT fk_attraction_popularity_stats_attraction FOREIGN KEY (attraction_id) REFERENCES public.attractions(id) ON DELETE CASCADE;


--
-- Name: attraction_ratings fk_attraction_ratings_attraction; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_ratings
    ADD CONSTRAINT fk_attraction_ratings_attraction FOREIGN KEY (attraction_id) REFERENCES public.attractions(id) ON DELETE CASCADE;


--
-- Name: attraction_saves fk_attraction_saves_attraction; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_saves
    ADD CONSTRAINT fk_attraction_saves_attraction FOREIGN KEY (attraction_id) REFERENCES public.attractions(id) ON DELETE CASCADE;


--
-- Name: attraction_saves fk_attraction_saves_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attraction_saves
    ADD CONSTRAINT fk_attraction_saves_member FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: attractions fk_attractions_duplicate; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attractions
    ADD CONSTRAINT fk_attractions_duplicate FOREIGN KEY (duplicate_of_attraction_id) REFERENCES public.attractions(id);


--
-- Name: course_invitations fk_ci_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_invitations
    ADD CONSTRAINT fk_ci_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- Name: course_invitations fk_ci_invitee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_invitations
    ADD CONSTRAINT fk_ci_invitee FOREIGN KEY (invitee_member_id) REFERENCES public.members(id) ON DELETE CASCADE;


--
-- Name: course_invitations fk_ci_inviter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_invitations
    ADD CONSTRAINT fk_ci_inviter FOREIGN KEY (inviter_member_id) REFERENCES public.members(id) ON DELETE CASCADE;


--
-- Name: course_embeddings fk_course_embeddings_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_embeddings
    ADD CONSTRAINT fk_course_embeddings_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- Name: course_items fk_course_items_attraction; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_items
    ADD CONSTRAINT fk_course_items_attraction FOREIGN KEY (attraction_id) REFERENCES public.attractions(id) ON DELETE CASCADE;


--
-- Name: course_items fk_course_items_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_items
    ADD CONSTRAINT fk_course_items_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- Name: course_items fk_course_items_note; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_items
    ADD CONSTRAINT fk_course_items_note FOREIGN KEY (note_id) REFERENCES public.notes(id) ON DELETE CASCADE;


--
-- Name: course_reports fk_course_reports_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reports
    ADD CONSTRAINT fk_course_reports_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- Name: course_reports fk_course_reports_reporter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_reports
    ADD CONSTRAINT fk_course_reports_reporter FOREIGN KEY (reporter_member_id) REFERENCES public.members(id);


--
-- Name: course_saves fk_course_saves_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_saves
    ADD CONSTRAINT fk_course_saves_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- Name: course_saves fk_course_saves_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_saves
    ADD CONSTRAINT fk_course_saves_member FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: course_tags fk_course_tags_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tags
    ADD CONSTRAINT fk_course_tags_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- Name: course_tags fk_course_tags_tag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_tags
    ADD CONSTRAINT fk_course_tags_tag FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;


--
-- Name: course_views fk_course_views_course; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_views
    ADD CONSTRAINT fk_course_views_course FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;


--
-- Name: course_views fk_course_views_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.course_views
    ADD CONSTRAINT fk_course_views_member FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


--
-- Name: courses fk_courses_owner; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.courses
    ADD CONSTRAINT fk_courses_owner FOREIGN KEY (owner_member_id) REFERENCES public.members(id);


--
-- Name: friendships fk_friendships_addressee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT fk_friendships_addressee FOREIGN KEY (addressee_member_id) REFERENCES public.members(id);


--
-- Name: friendships fk_friendships_requester; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.friendships
    ADD CONSTRAINT fk_friendships_requester FOREIGN KEY (requester_member_id) REFERENCES public.members(id);


--
-- Name: member_profile_embeddings fk_member_profile_embeddings_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_profile_embeddings
    ADD CONSTRAINT fk_member_profile_embeddings_member FOREIGN KEY (member_id) REFERENCES public.members(id) ON DELETE CASCADE;


--
-- Name: note_embeddings fk_note_embeddings_note; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_embeddings
    ADD CONSTRAINT fk_note_embeddings_note FOREIGN KEY (note_id) REFERENCES public.notes(id) ON DELETE CASCADE;


--
-- Name: note_reports fk_note_reports_note; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_reports
    ADD CONSTRAINT fk_note_reports_note FOREIGN KEY (note_id) REFERENCES public.notes(id) ON DELETE CASCADE;


--
-- Name: note_reports fk_note_reports_reporter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_reports
    ADD CONSTRAINT fk_note_reports_reporter FOREIGN KEY (reporter_member_id) REFERENCES public.members(id);


--
-- Name: note_saves fk_note_saves_member; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_saves
    ADD CONSTRAINT fk_note_saves_member FOREIGN KEY (member_id) REFERENCES public.members(id);


--
-- Name: note_saves fk_note_saves_note; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_saves
    ADD CONSTRAINT fk_note_saves_note FOREIGN KEY (note_id) REFERENCES public.notes(id) ON DELETE CASCADE;


--
-- Name: note_tags fk_note_tags_note; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tags
    ADD CONSTRAINT fk_note_tags_note FOREIGN KEY (note_id) REFERENCES public.notes(id) ON DELETE CASCADE;


--
-- Name: note_tags fk_note_tags_tag; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.note_tags
    ADD CONSTRAINT fk_note_tags_tag FOREIGN KEY (tag_id) REFERENCES public.tags(id) ON DELETE CASCADE;


--
-- Name: notes fk_notes_author; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT fk_notes_author FOREIGN KEY (author_member_id) REFERENCES public.members(id);


--
-- Name: notifications fk_notifications_recipient; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_member_id) REFERENCES public.members(id);


--
-- Name: batch_job_execution_context job_exec_ctx_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_job_execution_context
    ADD CONSTRAINT job_exec_ctx_fk FOREIGN KEY (job_execution_id) REFERENCES public.batch_job_execution(job_execution_id);


--
-- Name: batch_job_execution_params job_exec_params_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_job_execution_params
    ADD CONSTRAINT job_exec_params_fk FOREIGN KEY (job_execution_id) REFERENCES public.batch_job_execution(job_execution_id);


--
-- Name: batch_step_execution job_exec_step_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_step_execution
    ADD CONSTRAINT job_exec_step_fk FOREIGN KEY (job_execution_id) REFERENCES public.batch_job_execution(job_execution_id);


--
-- Name: batch_job_execution job_inst_exec_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_job_execution
    ADD CONSTRAINT job_inst_exec_fk FOREIGN KEY (job_instance_id) REFERENCES public.batch_job_instance(job_instance_id);


--
-- Name: batch_step_execution_context step_exec_ctx_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.batch_step_execution_context
    ADD CONSTRAINT step_exec_ctx_fk FOREIGN KEY (step_execution_id) REFERENCES public.batch_step_execution(step_execution_id);


--
-- Name: attraction_favorites_publication; Type: PUBLICATION; Schema: -; Owner: -
--

CREATE PUBLICATION attraction_favorites_publication WITH (publish = 'insert, update, delete, truncate');


--
-- Name: notification_outbox_publication; Type: PUBLICATION; Schema: -; Owner: -
--

CREATE PUBLICATION notification_outbox_publication WITH (publish = 'insert, update, delete, truncate');


--
-- flyway_schema_history seed data
-- 앱 최초 실행 시 Flyway가 이미 적용된 마이그레이션을 재실행하지 않도록 히스토리를 삽입합니다.
--

COPY public.flyway_schema_history (installed_rank, version, description, type, script, checksum, installed_by, installed_on, execution_time, success) FROM stdin;
1	1	create storage schema	SQL	V1__create_storage_schema.sql	1975877635	ssafy	2026-06-08 23:50:23.24053	37	t
2	2	add note single image reference	SQL	V2__add_external_data_tables.sql	-1556073518	ssafy	2026-06-08 23:50:23.302123	539	t
3	3	remove cdc outbox and legacy tables	SQL	V3__remove_cdc_outbox_and_legacy_tables.sql	-1097681467	ssafy	2026-06-20 16:20:05.975654	60	t
4	4	add attraction saves and save count	SQL	V4__add_attraction_saves_and_save_count.sql	1783200626	ssafy	2026-06-22 13:16:39.333455	73	t
5	5	remove member representative location	SQL	V5__remove_member_representative_location.sql	965714562	ssafy	2026-06-22 13:16:39.430902	6	t
6	6	add member profile image object key	SQL	V6__add_member_profile_image_object_key.sql	620528111	ssafy	2026-06-22 13:16:39.445893	4	t
7	7	remove attraction favorites	SQL	V7__remove_attraction_favorites.sql	-735946779	ssafy	2026-06-22 14:54:12.481757	34	t
8	8	add course admin curation	SQL	V8__add_course_admin_curation.sql	-1927799750	ssafy	2026-06-22 17:12:16.49314	158	t
9	9	redesign course route segments	SQL	V9__redesign_course_route_segments.sql	111987833	ssafy	2026-06-23 17:01:28.844521	63	t
10	10	add course start location	SQL	V10__add_course_start_location.sql	-1717695468	ssafy	2026-06-23 21:38:10.956715	87	t
11	11	refactor member id	SQL	V11__refactor_member_id.sql	-1454563272	ssafy	2026-06-24 00:40:29.119612	116	t
12	12	recreate notification unique index	SQL	V12__recreate_notification_unique_index.sql	-1554902521	ssafy	2026-06-24 10:30:42.795605	20	t
13	13	simplify course schema	SQL	V13__simplify_course_schema.sql	-1831664635	ssafy	2026-06-24 22:32:19.855164	51	t
14	14	add course tag and remove attraction tag	SQL	V14__add_course_tag_and_remove_attraction_tag.sql	-1320102009	ssafy	2026-06-24 22:32:19.93824	25	t
15	15	course date and simplify course items	SQL	V15__course_date_and_simplify_course_items.sql	73359644	ssafy	2026-06-24 22:32:19.970868	2	t
16	16	remove unused domains tables	SQL	V16__remove_unused_domains_tables.sql	-507010314	ssafy	2026-06-24 23:39:35.205508	26	t
17	17	change attraction embeddings dimension	SQL	V17__change_attraction_embeddings_dimension.sql	473543019	ssafy	2026-06-25 00:21:39.378793	45	t
18	18	create note embeddings	SQL	V18__create_note_embeddings.sql	-224017494	ssafy	2026-06-25 09:15:41.00304	59	t
19	19	add note tags	SQL	V19__add_note_tags.sql	1949580926	ssafy	2026-06-25 13:27:04.351031	98	t
20	20	add member profile embeddings	SQL	V20__add_member_profile_embeddings.sql	2046892164	ssafy	2026-06-25 13:27:04.474661	26	t
21	21	add course embeddings	SQL	V21__add_course_embeddings.sql	468128441	ssafy	2026-06-25 13:27:04.50821	6	t
22	22	add course views	SQL	V22__add_course_views.sql	1403214433	ssafy	2026-06-25 13:27:04.520873	4	t
23	23	course embedding scheduler and thumbnail	SQL	V23__course_embedding_scheduler_and_thumbnail.sql	-964690990	ssafy	2026-06-25 15:10:10.433553	22	t
24	24	remove note photos	SQL	V24__remove_note_photos.sql	-1586286038	ssafy	2026-06-25 17:34:40.927065	23	t
25	25	add course invitations	SQL	V25__add_course_invitations.sql	1254935592	ssafy	2026-06-25 17:34:40.976225	33	t
\.


--
-- PostgreSQL database dump complete
--

