CREATE TABLE note_embeddings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    note_id BIGINT NOT NULL,
    embedding vector(1536),
    embedding_input TEXT,
    source_version VARCHAR(128) NOT NULL,
    source_text_hash VARCHAR(64) NOT NULL,
    embedding_dimension INTEGER NOT NULL,
    provider VARCHAR(64) NOT NULL,
    model VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL,
    failure_code VARCHAR(128),
    failure_message VARCHAR(1000),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_attempted_at TIMESTAMP(6),
    embedded_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uk_note_embeddings_note UNIQUE (note_id),
    CONSTRAINT fk_note_embeddings_note FOREIGN KEY (note_id) REFERENCES notes(id) ON DELETE CASCADE,
    CONSTRAINT chk_note_embeddings_status CHECK (status IN ('PENDING', 'EMBEDDED', 'FAILED')),
    CONSTRAINT chk_note_embeddings_dimension CHECK (embedding_dimension = 1536)
);

CREATE INDEX idx_note_embeddings_status ON note_embeddings (status);
