CREATE TABLE course_invitations (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id         VARCHAR(128) NOT NULL,
    inviter_member_id BIGINT NOT NULL,
    invitee_member_id BIGINT NOT NULL,
    status            VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ci_course  FOREIGN KEY (course_id)         REFERENCES courses(id) ON DELETE CASCADE,
    CONSTRAINT fk_ci_inviter FOREIGN KEY (inviter_member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT fk_ci_invitee FOREIGN KEY (invitee_member_id) REFERENCES members(id) ON DELETE CASCADE,
    CONSTRAINT uk_ci_course_invitee UNIQUE (course_id, invitee_member_id)
);

CREATE INDEX idx_ci_invitee_status ON course_invitations(invitee_member_id, status);

ALTER TABLE notifications
    DROP CONSTRAINT IF EXISTS chk_notifications_type;

ALTER TABLE notifications
    ADD CONSTRAINT chk_notifications_type
        CHECK (type IN ('FRIEND_REQUEST_RECEIVED', 'COURSE_INVITATION_RECEIVED'));

ALTER TABLE notifications
    DROP CONSTRAINT IF EXISTS chk_notifications_reference_type;

ALTER TABLE notifications
    ADD CONSTRAINT chk_notifications_reference_type
        CHECK (reference_type IN ('FRIENDSHIP', 'COURSE_INVITATION'));
