create table auth_logs (
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    event_type varchar(20) not null,
    logged_at timestamp(6) not null,
    primary key (id)
);

create table boards (
    id varchar(128) not null,
    title varchar(255) not null,
    content text not null,
    author varchar(64) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table hotplaces (
    id varchar(128) not null,
    user_id varchar(64) not null,
    title varchar(255) not null,
    type varchar(64) not null,
    visit_date varchar(32) not null,
    lat float(53) not null,
    lng float(53) not null,
    description text,
    photo text,
    created_at timestamp(6) not null,
    primary key (id)
);

create table members (
    id bigint generated by default as identity,
    user_id varchar(64) not null,
    name varchar(100) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id),
    constraint uk_members_user_id unique (user_id)
);

create table notices (
    id bigint generated by default as identity,
    title varchar(255) not null,
    content text not null,
    author varchar(64) not null,
    created_at timestamp(6) not null,
    updated_at timestamp(6),
    primary key (id)
);

create table plans (
    id varchar(128) not null,
    user_id varchar(64) not null,
    title varchar(255) not null,
    start_date varchar(32) not null,
    end_date varchar(32) not null,
    budget integer not null,
    note text,
    route_items text,
    created_at timestamp(6) not null,
    primary key (id)
);

create index idx_auth_logs_user_id on auth_logs (user_id);
create index idx_hotplaces_user_id_created_at on hotplaces (user_id, created_at desc);
create index idx_plans_user_id_created_at on plans (user_id, created_at desc);
