create table attraction_favorites (
    id bigint generated by default as identity,
    attraction_id bigint not null,
    user_id varchar(64) not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint uk_attraction_favorites_attraction_user unique (attraction_id, user_id),
    constraint fk_attraction_favorites_attraction foreign key (attraction_id) references attractions (id) on delete cascade
);

create table attraction_ratings (
    id bigint generated by default as identity,
    attraction_id bigint not null,
    user_id varchar(64) not null,
    rating integer not null,
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6),
    primary key (id),
    constraint uk_attraction_ratings_attraction_user unique (attraction_id, user_id),
    constraint fk_attraction_ratings_attraction foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint chk_attraction_ratings_rating check (rating between 1 and 5)
);

create table attraction_tags (
    id bigint generated by default as identity,
    name varchar(64) not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint uk_attraction_tags_name unique (name)
);

create table attraction_tag_mappings (
    attraction_id bigint not null,
    tag_id bigint not null,
    created_at timestamp(6) not null default current_timestamp,
    primary key (attraction_id, tag_id),
    constraint fk_attraction_tag_mappings_attraction foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint fk_attraction_tag_mappings_tag foreign key (tag_id) references attraction_tags (id) on delete cascade
);

create table plan_items (
    id bigint generated by default as identity,
    plan_id varchar(128) not null,
    attraction_id bigint not null,
    position integer not null,
    day integer not null default 1,
    memo text,
    stay_minutes integer not null default 90,
    created_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint fk_plan_items_plan foreign key (plan_id) references plans (id) on delete cascade,
    constraint fk_plan_items_attraction foreign key (attraction_id) references attractions (id) on delete cascade,
    constraint uk_plan_items_plan_position unique (plan_id, position),
    constraint chk_plan_items_position check (position > 0),
    constraint chk_plan_items_day check (day > 0),
    constraint chk_plan_items_stay_minutes check (stay_minutes > 0)
);

create index idx_attraction_favorites_attraction on attraction_favorites (attraction_id);
create index idx_attraction_ratings_attraction on attraction_ratings (attraction_id);
create index idx_attraction_tag_mappings_tag on attraction_tag_mappings (tag_id);
create index idx_plan_items_plan_position on plan_items (plan_id, position);
