create extension if not exists vector;

create table attraction_embeddings (
    id bigint generated by default as identity,
    attraction_id bigint not null,
    embedding vector(3072),
    source_version varchar(128) not null,
    source_text_hash varchar(64) not null,
    embedding_dimension integer not null,
    provider varchar(64) not null,
    model varchar(128) not null,
    status varchar(20) not null,
    failure_code varchar(128),
    failure_message varchar(1000),
    attempt_count integer not null default 0,
    last_attempted_at timestamp(6),
    embedded_at timestamp(6),
    created_at timestamp(6) not null default current_timestamp,
    updated_at timestamp(6) not null default current_timestamp,
    primary key (id),
    constraint uk_attraction_embeddings_attraction unique (attraction_id),
    constraint fk_attraction_embeddings_attraction foreign key (attraction_id) references attractions(id) on delete cascade,
    constraint chk_attraction_embeddings_status check (status in ('PENDING', 'EMBEDDED', 'FAILED')),
    constraint chk_attraction_embeddings_dimension check (embedding_dimension = 3072),
    constraint chk_attraction_embeddings_hash check (char_length(source_text_hash) = 64),
    constraint chk_attraction_embeddings_attempt_count check (attempt_count >= 0)
);

create index idx_attraction_embeddings_status on attraction_embeddings (status);
create index idx_attraction_embeddings_source on attraction_embeddings (source_version, source_text_hash);
